version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: monthly

  - package-ecosystem: bundler
    directory: /
    labels:
      - dependabot
      - bundler
    schedule:
      interval: monthly
