AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequireMFA:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Exclude:
    - lib/pronto/eslint/linter.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - pronto-eslint.gemspec

Style/Documentation:
  Enabled: false